name: Actualizar actividad reciente

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
