name: Actualizar actividad reciente

on:
  schedule:
    - cron: '0 * * * *'  # Corre cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
